# Generated by Django 2.2.2 on 2019-07-08 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eesa_users', '0002_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='user_student',
        ),
        migrations.RenameField(
            model_name='user_student',
            old_name='student',
            new_name='student_number',
        ),
    ]
