# Generated by Django 2.2.2 on 2019-07-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eesa_sci_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scicenter_document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='scicenter/documents/07/10/2019/15/33/17'),
        ),
        migrations.AlterField(
            model_name='scicenter_project',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='scicenter/documents/07/10/2019/15/33/17'),
        ),
        migrations.AlterField(
            model_name='scicenter_tutorial',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='scicenter/documents/07/10/2019/15/33/17'),
        ),
    ]
