# Generated by Django 2.2.2 on 2019-07-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eesa_sci_center', '0002_auto_20190710_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scicenter_document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='scicenter/documents/07/10/2019/15/37/43'),
        ),
        migrations.AlterField(
            model_name='scicenter_project',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='scicenter/documents/07/10/2019/15/37/43'),
        ),
        migrations.AlterField(
            model_name='scicenter_tutorial',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='scicenter/documents/07/10/2019/15/37/43'),
        ),
    ]
