# Generated by Django 2.2.2 on 2019-07-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eesa_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_course',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='eesa_courses.courses_category'),
        ),
        migrations.AlterField(
            model_name='courses_course',
            name='hours_length',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='courses_course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images/07/08/2019/17/00/31'),
        ),
        migrations.AlterField(
            model_name='courses_course',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='eesa_courses.course_teacher'),
        ),
    ]
