# Generated by Django 2.2.2 on 2019-06-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eesa_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_course',
            name='hours_length',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='courses_course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images/06/30/2019/11/08/21'),
        ),
    ]
