# Generated by Django 2.2.2 on 2019-07-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eesa_courses', '0002_auto_20190708_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images/07/08/2019/17/05/43'),
        ),
    ]
