# Generated by Django 2.2.2 on 2019-06-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eesa_courses', '0003_auto_20190630_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images/06/30/2019/18/06/18'),
        ),
    ]
