# Generated by Django 2.2.2 on 2019-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eesa_courses', '0004_auto_20190708_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images/07/09/2019/16/53/15'),
        ),
    ]
