# Generated by Django 2.2.2 on 2019-07-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eesa_courses', '0006_auto_20190708_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images/07/08/2019/16/33/54'),
        ),
        migrations.RenameModel('teacher', 'course_teacher'),
    ]
