# Generated by Django 2.2.2 on 2019-06-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eesa_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('activities', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('issue_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='eesa_team_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=15)),
                ('active_years', models.IntegerField(blank=True)),
                ('studying_subject', models.CharField(max_length=15)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),

    ]
