# Generated by Django 2.2.2 on 2019-06-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eesa_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eesa_team_member',
            name='active_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
