# Generated by Django 2.2.2 on 2019-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eesa_main', '0003_auto_20190630_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='eesa_information',
            name='email',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='eesa_information',
            name='instagram',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='eesa_information',
            name='phone_1',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='eesa_information',
            name='phone_2',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='eesa_information',
            name='phone_3',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='eesa_information',
            name='telegram',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
